[project]
name = "academic-hub-bot"
version = "0.1.0"
description = "SIT Academic Hub Bot & Dashboard"
authors = [{ name = "Orbit Team" }]
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "sqlalchemy",
    "psycopg2-binary",
    "pydantic",
    "python-multipart",
    "python-jose[cryptography]",
    "passlib[bcrypt]",
    "python-dotenv",
    "aiogram",
    "aiofiles",
    "httpx",
    "alembic",
    "psutil",
    "click",
    "rich",
    "typer"
]

[project.scripts]
app = "api.index:app"
